from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .old_agent import *
from .pdf_agent import *
from .scholar_agent import *
from .wiki_agent import *
from .price_agent import *
from .boxoffice_agent import *
from .weight_agent import *
from .rotten_agent import *
from .tep_scholar_agent import *
